spring.application.name=event-service

logging.level.liquibase=DEBUG
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.datasource.url=jdbc:postgresql://postgres:5432/event_db
spring.datasource.username=event_user
spring.datasource.password=event_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#Ticket URL
clients.ticket-backend.url=http://ticket-backend:8080